CREATE TABLE SCP_CLIENTE
(CLI_CODIGO INT , 
CLI_NOME VARCHAR(45) NOT NULL, 
CLI_TIPO VARCHAR(10)NOT NULL, 
CLI_CONTATO VARCHAR(45), 
CLI_CARGO VARCHAR(45), 
CLI_ENDERECO VARCHAR(45),
CLI_CID_CODIGO INT,

CONSTRAINT CHAVE_CLIENTE PRIMARY KEY (CLI_CODIGO), 
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLI_CID_CODIGO) REFERENCES SCP_CIDADES(CID_CODIGO) 
);
CREATE TABLE SCP_CIDADES
(CID_CODIGO INT);